# Generated by Django 3.0.5 on 2020-05-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(max_length=50)),
                ('customer_second_name', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_last_name', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_age_bracket', models.CharField(choices=[('Adult', 'Adult'), ('Child', 'Child')], max_length=10)),
                ('customer_added_on', models.DateTimeField(auto_now_add=True)),
                ('customer_order_stat', models.BooleanField(default=False)),
            ],
        ),
    ]
