# Generated by Django 3.0.5 on 2020-05-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20200510_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='sold',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Not-Paid', 'Not-Paid')], default='Not-Paid', max_length=10),
        ),
    ]
