# Generated by Django 3.0.5 on 2020-05-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_auto_20200510_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
